<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>772b1775-d431-4e4d-9a00-e152cf3fc84c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\packages\ECommerce.Infrastructure\ECommerce.Infrastructure.csproj" />
    <ProjectReference Include="..\..\packages\ECommerce.Application\ECommerce.Application.csproj" />
    <ProjectReference Include="..\..\packages\ECommerce.Domain\ECommerce.Domain.csproj" />
  </ItemGroup>

</Project>
